---
homebrew_cask_packages:
  - { name: adoptopenjdk8 }
  - { name: android-studio }
  - { name: alt-tab }
  - { name: avast-security }
  - { name: clipy }
  - { name: cursor }
  - { name: db-browser-for-sqlite }
  - { name: deepl }
  - { name: devtoys }
  - { name: discord }
  - { name: docker }
  - { name: dropbox }
  - { name: evernote }
  - { name: figma }
  - { name: firefox }
  - { name: font-fira-code }
  - { name: fork }
  - { name: geektool }
  - { name: gitify }
  - { name: google-chrome }
  - { name: google-drive }
  - { name: google-japanese-ime }
  - { name: grammarly }
  - { name: istat-menus }
  - { name: iterm2 }
  - { name: intellij-idea }
  - { name: karabiner-elements }
  - { name: keycastr }
  - { name: kindle }
  - { name: min }
  - { name: miro }
  - { name: ngrok }
  - { name: nosql-workbench }
  - { name: notion }
  - { name: numi }
  - { name: obsidian }
  - { name: postman }
  - { name: phpstorm }
  - { name: raindropio }
  - { name: readdle-spark }
  - { name: raycast }
  - { name: sequel-ace }
  - { name: skype }
  - { name: slack }
  - { name: spotify }
  - { name: tor-browser }
  - { name: tunnelblick }
  - { name: visual-studio-code }
  - { name: xmind }
