---

- osx_say:
    # msg: 'Hum Hum Hum Hum Hum Hum Hum Hum Hum Hum Hum Hum Hum Hum Hum Hum Hum Hum Hum Hum Hum Hum'
    msg: 'Start building the macbook environment.'
    voice: 'Good'
  tags: amuse-bouche
