---

homebrew_repositories:
  - homebrew/cask
  - homebrew/cask-versions
  - homebrew/cask-fonts
  - hashicorp/tap

homebrew_packages:
  - { name: anyenv }
  - { name: ansible }
  - { name: asdf }
  - { name: awscli }
  - { name: carthage }
  - { name: claude-code }
  - { name: docker-compose }
  - { name: emojify }
  - { name: ffmpeg }
  - { name: gdbm }
  - { name: gh }
  - { name: git }
  - { name: gibo }
  - { name: git-flow }
  - { name: goenv }
  - { name: gpg }
  - { name: graphviz }
  - { name: imagemagick }
  - { name: jq }
  - { name: openjdk@11 }
  - { name: libevent }
  - { name: libyaml }
  - { name: lua }
  - { name: mas }
  - { name: nkf }
  - { name: openssl }
  - { name: openssl, state: linked, install_options: force }
  - { name: pkg-config }
  - { name: plantuml }
  - { name: readline }
  - { name: sbt }
  - { name: scala }
  - { name: spaceship }
  - { name: sqlite }
  - { name: tig }
  - { name: tree }
  - { name: tmux }
  - { name: tty-clock }
  - { name: vim, install_options: --with-lua }
  - { name: watchman }
  - { name: yt-dlp }
  - { name: zsh }
  - { name: terraform }
